---
apiVersion: v1
kind: Service
metadata:
  name: mailer
  labels:
    app.kubernetes.io/name: mailer
    app.kubernetes.io/instance: mailer
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    name: mailer
  ports:
    - name: http
      port: 80
      targetPort: http
