apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mailer
    image:
      name: vibioh/mailer
      tag: "202207160749" # {"$imagepolicy": "default:flux-mailer-web:tag"}
    config:
      MAILER_LOGGER_JSON: "true"
      MAILER_MJML_URL: http://mjml
      MAILER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: mailer
    secrets:
      MAILER_AMQP_URI: AgAhW4Wc9xcxXhwuJOiiH+jNby6P37DXfp/SsFKY9rWS6m90dMKSvfx+mUgW0OQN1t01+Meh9tLnnkGWuKU0IJqduwUOPf41EfHvwSDNrMgmi9fxJoQW+7+5ZlTbI/SAHvECEOlatgy9C3I4Lvj76609nD38Kq3Gxcnxke/5bxZ69/zLaxJ5575wuJ152lSxoYObVYzSV1+1UhDI271LSmspbbFq+zg5H6bmmKT3TmeT5U3/E4R+blVWToDgxuQmu3a8TzG81fGso2U2vOK75fXt8lW9fmRnw8sMhyto/z9ecxktlRHiImwb6QVqDnQjiFdLPpgsnMAXP/S/aSamNTbSNrCi+6JbPXltk2z/8JVdyiNGdeAatacABsYp+PXchXFJNhsTupQL7tyKl/MKEp0tSUe5+/b4lbQox2vYKxnk1U1bnIJV8y1QEUrz/t4DwfLsYvJjEnPVum06XpKpvNTmgcZfhnwgwespmu7JXB/Ihtrv/f9dAHM37tZrkqXJW3ey1EdA5zXSSWutmVg5LJNDMaXeSobzZndIVNNgZrYi7M0K0w6lZa2X/UOcv9LATpd9Z52ONHkBgJxVUhJc4pSdssKgZcP/gc+xzBvxbwf9NqUKujR4g1J8PD4ACntOCFyoAgMbeMBvpxPRcisVxL2PS5/K/N4m1eL0Djwc3VXNFdSuB4j10NFKjOLOTcRgUOtmuw08vXGRySrVtBKhFQtIGV2oeCw2xgigxxLFvuL7XJYAeFX7vxgJSc837w44+U8VGcI=
      MAILER_SMTP_ADDRESS: AgBQ4jvTdRkADF+EfPXdCT3AR/gm9e0l8Z3vDDU/aQIp2Yn1ZfzYZoVO5qILsD/b4oStzQ98V4R+WmQe3B6e9vfGvn+YtyPePkTkCXBr1RwDRNPLKLokoKorAbnUW/VSSE8GIEDP4GxRmbD53aUH2q8fcgN1Qh1i21xnUxQyzfs7Ss86xDb8ynMhvZ1DpfXh9KO+b9lQqZCs8ZgVyZkmb5aPtB0DmOzEIKVL5ktTZL4AipemC+Rju03N5VTy4nSqrLwZB0n9X3F9LqU/MON6+3pZos5x3eVCxHdhEPUW2lnj78Dn7EASzSpRo5Rs1KaRyrO/izE14yZ1XueG2NxZhgG6T3wX3zqpN3kLu9Y3YNACcrrmbxB1H41ZczFOaFJHWRLsvryvATneKEzjwubvBc+fYAfmGQvxHhGAj0MkPffRSxHMGtoI8Au9dbUUnwZpcFU35+3gpwcSa8E42WG/aAvuP6G1AJiDWhZMMt0kJK5ue76pNn9ovyNnB8r3IKLxHWMIwuzpOSoLz03HYHTPYC2+Yefk/vcaHj48U/jt8YeFBUXXtGZ5+gZY7GFtf6PBrz2K64vdW1TQsZDBWWKLZaSeypF5+Ur62QMIIIbUFm9tq78COCFIiIfOky6cq1DaEtjuM0JaShXzf0w/wcR8jYeMmtZkqBTcjmQXcgCnwZf9zNk7tragASqcsG+vkb0cAr7fZfF/yj4JZmM/xDkWjKh+Uz34Co8=
      MAILER_SMTP_HOST: AgA/HeEq61vhxJNdyKB0t1TfYJPJfYhtF9n0YvXnlFszFiM/LYXscqcdGH6IyHS7PPtwOBpH8R1i4XSA21p0oLZ800QHJt5nNO24RZJVHqn2+bCsJTkShKrRUEwidKlSdtIKMZm5+RRgnlyBkXZtMCj2/dF+TYokEMG4TXfiq8Aaac13GzSDIDnOlWeqQKrR/Wi8fMIqWDMRbTZmLMKGf+S41NuDAxtJc8clYs2WVhAOAL5r6jesvTGRWuevPWiNPziBOy7y9qeMQ5129i0HBMl/GLj+wKRilljRjR23Z8hspk8Bjv/W9tfdH18Qt85hXyXkxYM0pjCMMxcjRhVnKUD+2QoulZMb3W7Q5hRGU9PTLP2qJRrMq+z6DDmpib1lXnwjJ4VVHeShIXrVdYbG2NdipZOO2c93WkkY1FssPL3oVxUpogOyHwPLw64R7q0e/5383s50Woq+WxirBkJwlq51hGUDpT9aBuHzeDX/F+VRhA3C5iilVbeS/5/984itemdDopf6ijsWMF59Ww93qiyhQxUqPsq3jyM/a+zcNxv4PQ8octHINttno3YVyXO0iJSJWlpGxv62Cq2w4t6gcC8VBm1gP1WvHOG/qMnE08BaHLYexnguZNUkQmtGh4aq0dioMS82bv1dMusXVHwRy1TmY04apHMkPZP14nhBsxTINEctUEF+TGFJTvrwWN+CH4nrFSf2igKluHoZVBXh/Ow5Ug==
      MAILER_SMTP_PASSWORD: AgAUQ2iuReoFKMLCdWa8UzfvNGeD9FPhTO+YDbhvr+3svMMHx/9SLm4qbD45qPvJsIp9IcechWehsefMlvANFpdf2Jv9qObadCNNJSP+dE5YjdpiUbvBkty5Gp/FwD9VBmsWt8F+Bk6MeYjuea9yU3fxbgk8QVjR2gsJwqr1KXx1TprEdUaj+L3TxkUL7E67ytTPuGxFEdmP88uFLw7XCjtTv55QWMuk2ZWgOGkJ5v+NiV1/Ocq4fzibBT+N/yHhUNotoFMx4S5tq4LcQhA0FikXyfTftQj7yPUOzn7hLVq6jF/EBClxGwVipJB06WZRGVOZtn6U+asyoAQd3Y0UiF1cJIJsnFWwoMrEm8GKSWrhY2ZCvmgkgeJoSOlNwBKeGEbIyjWEIgV3i6EGWd8+E/5divGpRpZnqPrLh++UeV3x6YznpT+fKp2CucV9qXPtF16Lo7QvrjtXt6CoeYZJMHAgO82okPvDPtqgwDhP7ASExiD8j74cK4QDLzWNXBsFzbgZhl8VmDteS//6Zs4arS4mOkxRauOPM6rwc3LlpiDtv5f1QqQubOoPUEMRBcEDMQcEikSXfoLOGPAYuTR3Q98hM79CF0qwiXow57rB/Z+KQm3XNG3RK5Gf3DwQDXTDed88SwYvBQpIDUTPE1nJrQOSEcvsXHlobnGKw8ps+2sbKlw8BaBAuJz5UNxQu20VjTN2aTnYLshOLoCqSYZ6/9Bx0LLvgZ7loUClbOr09RkmbQ==
      MAILER_SMTP_USERNAME: AgAS+8kUcl91cah3IEI6JAmOJ1DR6Mk25w+lxPPv3WpmZsDARhPK+JQGMpJdq3MCGtJtG6aXLbeBqo4MutXGQf0VawLyHLwBT3xKIdLqhkgCJg2dFe4YEQVmHtby6PVP1TkhtLy+47wUqL1BVicILY4TSA6xL8PrGcwTkN0eU5VAcg3d8pry+sUsrpMab0ax/dmCLZv8PaONWqExxCm0Q/MrhFutYJmSROUw9RIauK4NiLCrZbGGM14GGE1qcmk1MFAw7zuzgWDxTW84FH2wUK0Nim5IXGQbR++1K/m+9yzO5FoVVkZqHMrETI5DNPoB4GDbLLk51Pb09ZAwP5ipRTK5kWfOpscwBBMA5WyrYBgr1ExMlIwf2NCU8vHpZRnWHDvZZWAKpBSB0V6cKeN4FE+jyHxxcW5U1xe7eqkfys8Zbq4VNW+7qjCHkbK/qX+NcnMeXJ5/ygCfwNkO78Ry4rcdsn+KZT+mOuxJqeEU3UcfrcNm7FSi65RaYFLLWfGqgDnsUylwSdxdZG4rwIDUdw7faXW+idXdOwaxtZKXZ0iVIpMfuEKO85T7i1KwC3IzBrZdpwNregtYz04AEZIPrRkaoMh9K6tEGQ2NTSC/fq+wyOL+IoK6y/mdfPguy8Jq/MWPC6oH+kpVlyNPMENnN93Ry2KmSn9Z1ZPylmDk71RTOVvJQ9mPR9ApsLCXkdfGAOE3l+ZoRDPIKbR7i1VFX3zvQwAWoQTdLW0C/BiobDnuLQ==
    pprof:
      enabled: true
