apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.88"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mailer
    image:
      name: vibioh/mailer
      tag: "202304272021" # {"$imagepolicy": "default:flux-mailer-web:tag"}
    config:
      GOMAXPROCS: "1"
      MAILER_LOGGER_JSON: "true"
      MAILER_MJML_URL: http://mjml
      MAILER_TRACER_URL: otel-collector.monitoring:4317
      OTEL_SERVICE_NAME: mailer
    secrets:
      MAILER_AMQP_URI: AgAZVNe+mFG35KvO5jdOhp332l6959+XHz+KoEcGronKIGgzxX3SD6TPb88MhzNjB+EpCwoopPqCRI3xDFATRKYPntTeii6pFcYTHK6gADPAyKw4oJ/yFb+ti5TtBqkuruKoOQdr79k6+Z/8QfZ2W/F6ZBANCKN47DYkUpFmqPSC9+nvfHZHX6kgQ+VsBW56wbzOXEgDyoNoI+3AdF8Q5b8BE8R1dKG6Hf0LKsNuM3UinZHV3TWV8aYdgufoWhwANSU21DKFUL1qNiiZ7lUy9ts/PSPPMTLx0fXxcmLB8ObHZzHjRlfagikz5D4F+Fh41NWcTo7SHjZBd7iPkCGdGvQlC3TvDaIlIJ1o2pjm36D/ROICybaVy4p2eK9vU6rnwIZ6XLGIN58+baMFxP8vD4BYvNUNxWk9VXuS9xzVwmJsOuyQecnlW01o6q/zWXi8XydRZhd/WFIMzSF2aJGVWVduqB4E7Y3TalS/8cckKRgCCmra5prd0hOurPyZUvyuVHA5x5wesvgEqm5bVG/nb8yxZuaZx1P7MUqGDZKRsZdGYAQDRLkWugEa2b3ratfBUBLZiR28W/UrtEv/jHuvc4U4+0zBcijoO0Du/vF73Oczy739PYoIJEWpEKM3BHX/HFBzl29u+leQ6ccL7arXbOTWMdMvrzfIVS4qVfUUBCRQWQPD5GspnaeR91C+nImflGLzQMBbSoqPdjpnX2IvDgQmVCqopXeX8Fx0q6Kxc16+QGUktB4b/ZZ7RQyk6C6XmWtOJ1Q=
      MAILER_SMTP_ADDRESS: AgA0QDVxpjye2tmyNQ4ZbjAXKimMRxECHmd8dSOzHYSgKITCGvxH9APQmH2Bv1JX6xhwMAgq3DLrmvUeyz3UcYDkZaovjB9uLAzbrAhRBo+UIeeRaXI160ls7x5BLcPn/AN9vJkbA+3CDHBLXm6QJeDrrU6J4jiusGv2rhj7ppaS1uzebA5AuF+17fO2OHk7CaQYq8UZwo1aV1baLlKCbi2XEZVRop+30vWxdwkQecUe/MSvtc8RDyVRI3pgchoEh/FffB5KecnOqDqBB0hrfUxxrWY+lWDaKedHf/DXjYLDqZEVyEEFVowsMdXbVQ3xbRm4fGVMEoXl2fM9VyOaqjNo6vw/uxtctUdN1PQDbWM7VEH4So+2YB5jSs4Aa4fqbf4J8TcBhzQd/M3PNHiM6StteAIRKp2UcMEAoOWxjTbGxrePqP7Wx8xsjzaMiClJ7l2nmByYoCVJ2YkLPGS6ovDnuHCkVcqGBQ9LgRqKj8GZ2j2YMXenxYzNjBEeehpA/1rPyvOXPxFBJ6FUR2Lrss98nNFtccWM5vpZDrtOJGK1Q+rrvh8IZURFffUXZETa/QGAt4HTGzeKop3cOJxUv4X1146aYRLqtfx47GgKsyNPSvJleVkwsn1F6HT82C/zcrF8YjV/+iQkDRqZf/tSnr4nbAX/ki3VPRN8ZkfCXC/+tTHzn+ZvcB/B5vAeLxcc3oDCZFSnv94EtajPkAqIr/xTECI9B67I
      MAILER_SMTP_HOST: AgB+YZ1TazxL8mJIHX/sfzaOlvUt8bESiRpafzHjeg7mftv6Cb/xo9URCZhL6z3smnBy88UTMNz0E7P9pyKbVHwn4Jal/cbUtkuhTa+LRmuFMsMnhh7iZwzrRBTsmGAfvD2/0x6mG3TgFD/QrDX9oyG7X1EptCC3It0r5O/cP/xiGjFWy8iHWhQu5Ivvm3DF3KlJnFY2s1JA+B32Vp03nVtHbNRf7DkBqPYoM//An5cwUvPzZQjJ1SeFmiM5JM7asWPkDTX0M7CHnTifvx1VeNVMWseRmwl0U9VTvLBYJPdZ9z3lbdEZrRlCPLhSjMhqSoEsUhBG4lB9squbMYKTxAecCfMAja7eXN+dzdM9NL5UQ8jJR2BTWv8pnRcUBoCiy3abWY/mBRgFMQvWYcjGNrfGUf7/Ku+eUYhaxZJXeuaHc8DX+kK8t6YNzPFV4voeYgGjT8Hd11gGkCuQvxRpEXwO2fWLNXjD30fA8uMqTmIN8UzezUIPJwBf+zyX5WnjUDbFzfNdjN2b7cAWW6xqdlXwinwvVCVu0w6mnOnKZ8BYZdvxv9PGb78ldM3CbKdp9aoOYYDUcf79eScgbcCw7fE+qKxxoXe4EfYDEd1Nits1TXkN5V6fD7Q/lTnL4sgL6KDmE9oK5QLQ8SYY5pRbrzaoLMdK/Lv6vu/Zyg2v1jUc+Lf0rPeG8bKdlv1OCTzSEbWDUhf7B8qZHiuwC9M4vjO27Pw=
      MAILER_SMTP_PASSWORD: AgCUYsveS67NjOzEKmhakJSeMkg6Tsdw1m9w3aj+X28CU5atFP0HQhUlOsoyGT74NhMuuvHfjlh6v/g8vFvcUAwq1IesRhJry01TX7MDeGfI8omcTscPiZXZFkb2a2wKH5YhCe35lpMf+39zJvrGCd5FwGO82HdNwFoXMIWk7myPciej8UZoe22kNeepGgdyA5erLWZz0ri5+RQe6BJfbMf34nNmo7Rqq8EBj6pSuxp9Gfvipb39ZxmU+sIRVAAcusRBeu+2ybk4UkeJ6uYCNYG4glHHELc1LoB1RVhVBPzSYnbOSl0I0ZPkrPZ1DogPMqPjRntWa3sCPVgyU7GwRTcEZO7mzDjcjQuOHKiGtiOU1FPOaoU1fLiP/vetzsPH++X3r7Wos8bi3bG5gnE+H1waldZdOYis5h+eocqLa9nEr1sNcqpKEgA3fut3zFe8lNbC6fx7yTjx2hjwO5qOR2DbjaagiT0eWY5WItgON4ht8X2UfkiD375Skml5IQGl5w0h71iPL1IUskRcdhdKTmL77O3iFP5mAkysqwAw3OlpOlJHb9JW3tdsQUNUuLlETLYRajYvmKZRUK7aIcRx54Q9rJjs877ajCKcb9646/NE8R7SEcRCXU9Vpe3BSx9QhJnfkw9CDOAv9pHJdbyYU1KTe9I3fWcfJEAJSUYmyfJeN9Dt3y6FqQZ2eJ+dXYvCIFdvUyem44i1VyP0TaHrw/3VaEkWmHedp0pVBcxacjMGeO1tjvI=
      MAILER_SMTP_USERNAME: AgAhfjShvP9aez+Mmwf2hEOnamwEWK3ByocTg6X2GyVtxn57kIeDtqK91C+GUklREYtY5KGOmz3dYQGRPhO3RGuQvarn9i/vDYHCIGRfCY0NlSw06qFfGdYPaEBqvxl2XCzAHJb/OmmyAFyadfb8xcru8L0iQ4FijcSvwp4wLm2uav6ahjUPOBeDvKhu+R/GuyNSHW9ebKsSL3BFpC+a8KSlXXFgw//yHLCvRnc5R+PcQbD5J4fvzZLxpRxx+hoxod17zfUQkEF+zm5gwX3bSmXuCDJUZz0K0jn2ppwvGOFASveg7qbuw1tByihe+2waADT3LYeundGKhDQ+4e2KeSb0ek0rK1eeRjtVnH4oI+LOz10UFEyTWYNVpeh37uLdFZcV1/vCDLfRHLUn+xJcizu/1KtPGOu726zwjDmYSxmknombv4IZF31wMU2H+JzRQcTHmkz2SvZbtUScWs0n5VaDuuiEQ7jbgZhRXal2i8mFBErvBGtcakpW4IoMdUkpi6VU5eP5FPrrxSGiRG6c/c2WYADSkf+V8505hpzD4Nf7k/C1GchSA5hGq6xXKMUgD28lEAV1oKAeTSKiSJXnfPA9YZaagy5nlV8Aq6b7hJ8XICltapqTqd6qxtJM/byughnUXOwVcq7zr+3rrMVWgTSuQ9VPic1C+eBU/ah24sobDljrxxzbbeYV4ZDPpzLyfVGMmPBribz/cgieaJJt5R0BhsrHH8Weako3cNgUr85e3iJvNcE=
    pprof:
      enabled: true
