apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.86"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mailer
    image:
      name: vibioh/mailer
      tag: "202208240923" # {"$imagepolicy": "default:flux-mailer-web:tag"}
    config:
      MAILER_LOGGER_JSON: "true"
      MAILER_MJML_URL: http://mjml
      MAILER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: mailer
    secrets:
      MAILER_AMQP_URI: AgAZVNe+mFG35KvO5jdOhp332l6959+XHz+KoEcGronKIGgzxX3SD6TPb88MhzNjB+EpCwoopPqCRI3xDFATRKYPntTeii6pFcYTHK6gADPAyKw4oJ/yFb+ti5TtBqkuruKoOQdr79k6+Z/8QfZ2W/F6ZBANCKN47DYkUpFmqPSC9+nvfHZHX6kgQ+VsBW56wbzOXEgDyoNoI+3AdF8Q5b8BE8R1dKG6Hf0LKsNuM3UinZHV3TWV8aYdgufoWhwANSU21DKFUL1qNiiZ7lUy9ts/PSPPMTLx0fXxcmLB8ObHZzHjRlfagikz5D4F+Fh41NWcTo7SHjZBd7iPkCGdGvQlC3TvDaIlIJ1o2pjm36D/ROICybaVy4p2eK9vU6rnwIZ6XLGIN58+baMFxP8vD4BYvNUNxWk9VXuS9xzVwmJsOuyQecnlW01o6q/zWXi8XydRZhd/WFIMzSF2aJGVWVduqB4E7Y3TalS/8cckKRgCCmra5prd0hOurPyZUvyuVHA5x5wesvgEqm5bVG/nb8yxZuaZx1P7MUqGDZKRsZdGYAQDRLkWugEa2b3ratfBUBLZiR28W/UrtEv/jHuvc4U4+0zBcijoO0Du/vF73Oczy739PYoIJEWpEKM3BHX/HFBzl29u+leQ6ccL7arXbOTWMdMvrzfIVS4qVfUUBCRQWQPD5GspnaeR91C+nImflGLzQMBbSoqPdjpnX2IvDgQmVCqopXeX8Fx0q6Kxc16+QGUktB4b/ZZ7RQyk6C6XmWtOJ1Q=
      MAILER_SMTP_ADDRESS: AgAbwhh8BqXMhU8J/zOFEK30yAnt2o9d8ZHsOGkgR2BChfDzgGGpgocHVHeVihcJm8MafKa2w3FFGmNkIQ/zHUFLNf1k0hdPe5AnBAd4FIvqk58BsM0sDS1OOcFRPZVQSVi4VCB5atp7J9XzoVB6D3so7lOSzNXn5SBaQ18ehF0WLaeVzhYCxqnriKCbTfSZTb1ef+rpDQXIfakb65L7tkKu3jINXjcQiBJNO3COPWy9uRpTzF5vAnFrGaI/0gRJ+kUJUDTVGSntREDiZsed0gjAr1wAroxH3UqBnMrwfMO9i2fWzdtbeeczZWVqqqhNu41R6sxBet+MMIC6DoYeI+VzyG9qDoQG/BzcYt+H6uOd/DcLXw+rxqopVdjzs616L4DrVI5WcXszmolvj3tHQegLUshb57elu3jiaO/NF0eGAhPpT5slWcs5g/pPGCjyymLGa1hV7jocgxFAtIw2ZSxHtOdsBGulz+iNTfL6fvPbOcwgBTNJZ5GbNkZUsXn8Yz1U8uynQtHXLrfvIhdCpNoIjquS7OcrIwaPwxQrosCapqueZiQTNURy6l9p17gQs0fjkomgPDboXKzKwK/um4C2bo6lkYCp7EAzL3Ng+uGMpwuWdgdAUh2ZkHWMmzXDK4jWoKcKPti+z4SORrq67E07LIAPuquoWvhg5pheSmoLoxRwTWV4C83nxumbs6ke455fpld9s2KBVx8GCrZ6jxlDyREfNB4=
      MAILER_SMTP_HOST: AgCvoQAIK3t2juw/g1y4ljRXZ6PJEmMsu1dL9Vgr7v4xSFN6+I1nSLR47IpKpRDaHfSu6IdSxiZavwvpUqNnuAW1/ixAn9sUHFtd/q/AwEq6uf5ECCG1nmv9Bvb6RS4K4IOSFcf49PL3900YfZ5kCPI3kG+LfF4PEdDJQSUsozotz8MzVZjd/W7IzlyL9Z/lvw8PO7KKu8k9fxxC6kto+oDD++8PaR5UGJA90UwHm4lj9Cg4exjiIHFd2yyIT1RjbQxmmDP3zq3FlDyBmehi13aUvfLKWkLfC2ZbnxzOa1SeqHS8Vr99TbHmK7fVix5MV7izlHYT/yhl87kPCDGxMRS80NUS9O8GjC343Lxq5Zi9+YVEdZJvmnCm7jb2Hg4/84XdueVfRq2Jp9DuFh9XQMMsCBur8375J458ag2q4y6bJB9moM9fogpTtKPyZOIadOsxcUk1MOKY8FfgDgjDPwFyOfqeYDX5kGesKmwahQwF1c7KopfFYb+iUR1D6lXZ6YZ0sEoWEDajTtd/yNcl7RLz1WbMgfh9Ok36HolJSG3MZmHwQrIElEb7DKUC/UtCAKXAzpwpeHyxYUJgiDdbbITn1562XL/trJZE//jP+NgtcxzFzFEIxNCy2LDSLTc7cHrfKXvMX6JOaCycYUO9+1HZlEtjzhuT/6muKLfjdeL/+3a5yvKbkSEe9+kcExR/y8WzSSLI3sx0dKp4WAVqtPBZSQ==
      MAILER_SMTP_PASSWORD: AgAooQDYQNHm/2j7wQXfwxSzqKs/UWQ9CQGdM28jiucn1JC9b07lzVxfn2IW4hB/DiYORQiffnwfB7ePJI5QXCABoZfCN7Z1loCyhNwNE7E/22jQRc4u/VhCtrcu6n/Du7+CVkBvaKBkhLo/TNJED+8IjOVvi5mCC0qvDhWWoVNoQ3tZmkOerMdOZ7jizQYxTAhdAfi81XeflITumqoq8cTIJ55PDokz7+FlmZnkJtYtrfWky5ZZ6p8EqyeIURJ5Dqvq98ueXZoraebqKR7gt7MO++JCBWQCZ8oTb9ADzfjG3EG5/xdePjFvUZVjWAvkLY2uWqfS1mtMqQstP1diLv/M7ZQjQwEngelM1SJbOrvGwf06QJRNM5w/34TUogE9c4vI1gVLYawZC8srB4IOdj/RO+nIFRZbNKy5d1EcdKi1eVFO6UfVwpgGODube62W12M3xSpKmK0IW7eET7AfWZgeMzg6d2EUNLelqNDdjDbPAZArSwZ0sChHzjVattKhxbduFwEAsdI2RsOiJ/s8K1Jm1iN95ggcOvtWdgtFe0aY7vw3GXDTly9UPiw0seNSU+gInaLFTATHvg/jgEjgBjOSPTyMelivWtvuWjN9s00QjbcDb5fRUYAOAzkrOCRNm/I4kjfgtVDEYvV+xBUMYjCn2Y3VRHwLGjdCztBWA07Aiu1jIDzh+WMOD+0pNq3/f3SUGypsB2Sqtgt2uFkcV3sWmO/+ArpyoVgGLHKfkgU7bw==
      MAILER_SMTP_USERNAME: AgBksFKdyji4uAobEHIYAMXuHReKUE9yPKdrBCA3K4eGO2etSSGbHi00tcMAyf2dQnuJsS0yEQ3vF7iouGCxNQHJ2CckBivTp2GVFi827mdvoZNZsPhnyGMUg7jeyLZrglcbz/E0ftr1Q3xPQnm/cxh3A1ciFbeFsqDmDGGCCbjdh+XEGpdqGvKfPKNMkM8Ju06iBSUqf+Q3Gt/eAhZtHfWqwjZVtVG4ZqSPKBOURinSgPs+N68joJEpK3cB1/7Z2C09Bjo7vEOUI5MY1gCw/JCzxe/zcyYkHQt0q+A/Wejs4JH2WEKvoSZwX/fUR1G81TSgQOuihvX0DSOVomUztINkfBhdz3XkMdnK0MxvfQN+KZvphk099NknXo7DcZ/N8kEveH3RrdOeqe3t+dFbDRGm0rL5X8FKEH+gw45o8hWSrl1TC8SKMEjICA+eRC9Kr7PvfXJKmOiawItYNYLlZB9aZsbhWOx5oXjKolCEEQMTn9nFYTh4lxo3w3zSR5/jsPpA8FgpIkYsT5nDvg0U5OQqbVzExbDpfydLcODt4Ag8J55wjUAvBrFOXhCmYuaG7BQDP69prtou4AOMasrqism5MYQ1rO9UFpn1mHGCW6bDsmSYoNhxcb21B3VEWtpZCz643W5krFiEFYSt9JiZEu0bQfUEATDovwOZKzUrQYReACxdLv4sUqva1j64dX3k14EE41CAuotWBTUU2p/PcIow2LjfDGwlU6iw13UV0//cVQ==
    pprof:
      enabled: true
