apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mailer
    image:
      name: vibioh/mailer
      tag: "202207160826" # {"$imagepolicy": "default:flux-mailer-web:tag"}
    config:
      MAILER_LOGGER_JSON: "true"
      MAILER_MJML_URL: http://mjml
      MAILER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: mailer
    secrets:
      MAILER_AMQP_URI: AgCfCccHx7WXWKmu1G1+fqTox+0rppqyagq9HxjKvDN/xuiy215eJ+f5NmTaqtqQuiwig7SsB/bukolmZsuo9FXDdcP4YL27hXxQT1+alsvMKVmgxFlFPSPCvPkDSS8g3g2UMG8rGfdD90/JMDOE2mfcrULccjK9Nvu2hUNscK+Sm++GsDZWM7au2Oyfd0MzKPOkqhicseF0hm3+a4IO2RB5Rn+3s4sCWuoNdANPeSiYDj2UL8nHTmDptVjYKAQH0GVY397QTLqhJRuYvKY0UjDzrQUYBpg7JR6UqkRQmo8IOHDU2U9KkkphduqNF+2Drl/9Ad+jqrkeHMZ57G8k7gqlYM/+i/IkbBu/oGoyoblWsI3fZlYp4fzLzIxDeUzWDq88kxaVB2q+k2eWF7UWofgL8182eo695X4QK3LM3niOKw8kqOg450s9+YwuztsNOU1P+OzSkO4EaMK1EIsWXiO92m4Jgxs+RKfBh5qFvImWPPDLR3W/SnQJceh41xHtKnOqYaduob6sN9Zz059I3P+BuhIL67mvNRmDIA9yWFK+AkqtC8NhrvHc2tVvjrzZhQzRPuMtme/FYcZxx0Kk4ZLZRAvxSJ5Qy2hH1J2fN0y/RbAvpNf5VhjhL4SXO9g3TzZ71cM/Hqlrbdcy3B0C5fSr0owCwW/q0g1p3bX0ZtK/hpEmXGYk/TzdC1wwp3ySRjtp3DXfulb8KIDHHMhMcPvVsl3PGDq8DZVzRJsk0yYblifW+nzHa0WrNf06da7F2vcSiJY=
      MAILER_SMTP_ADDRESS: AgCIRpiHTHyo9VIBIA4oMbPurAVkqZkSJ9U7deMhHU5VnfjklIoVwqaZqicpDQk8HYvo0lHxvoMc/+6BK3pJh5aSQLkq8lcqkDW7IYL5lB+u3pve8dp+Fju1EHb3sjtoTusHylVrBfSljocoJFChEBGT3H1QSAHuSYjo3qi8S33XAO5R4caqlmigYhO18gitAv6LIDgW6FU+5yj8EHrH2Ax0smVsuIC8QS8QfTJMJ3tOoDrzb3s1DnwemF1mVNqIyNGA+6tn1qTirlzNXk3hm4jp3xDiZb6g0+wbEpOSJj+4xbRjdgmKbIxEQfeYo/wjuJRYLqWNyQ4h8q74axqodjgrTEcXUylLI/WgES3yF73mUuJG6DWqtqrHmx4cdr7rkr0i68umn678K4ua5aceMMuygMjLMmgiRpT75OJBAQFxLyCEqF61j0nuRKNY56zobUhYKSwc7PuahYquhplu1z+u0On0lMzyAaWpT1mdx3iXD2zlF6KDiSHrJ+WF1OYMiVJhG0Ht2tm34xK8tmoQVCmnocaB0AVQsWw1ZVoPSL+x028VTOUwsQIV9eA5wxBTYevd2mKyjTNPf1jP6U4GfTWYjCaZ4UufAHfX7PBFCfFoeWQvsKwZx0w6U2AL7LcuRNetumGzbx3EkojHJhE0/sP6DdVJRAtzzYACr0C3Ys7FAsSs0wXO/Y2ea0x5qUKJC89eDYDooB1XROrVn61u0sCmR7Y6sWQ=
      MAILER_SMTP_HOST: AgADghBcSPGH2WLVDMLzBTuIFvdKIN7iUeaMlAUaU5tFg/XL0q2wIUgMmde/payJBzTto8Cj4+fMMOaFu7d/OKueMhy3tFVQF1S2CfbS1NqnEuiNUEgJJYAE89Q2/RbHxBiST+6gNa3Lb030uVQrjLPG27qE84F4Jjt9r4uAY/frRv/XhS8Sm9emEnA62uL/N+J7yY5aUG5TMFTrtq+sh+I2Q3hqQKlQPFaO8/x/em7ETXafpVFVvun/9T3V0jX1GivkuC7Mn9Ayp9SAEDSo1aD7iZDm3zkILHiTOAG2ZYws6fP7B2ZG2NkbiidUd5i2fmKNj0hS5pcg10TQZL9EKjDBpKdv+uEtxeRu607Qr6oq9iTR+VQhjTKnmlR/RtFTRa+0xvH8PMVTKrX3Ubqg0VFapdu4BjVTPdC+4wXd0EE3jioj3NhAkrKyTzIyXTgqwdhyUUG+Ao+uT+UEqUaTHqfwXw78Xhbm0eSf8NuZM/yI6s/c5YplfpQsnOp8GZ4XvpisyZy0nYTbDZ1NTnGju8S0/vL3JsbO79UP7N319LPG9kmEM2+LXlhThMG2c7a8BnDdfnpDLf6W6s1faMCz4Ox7Pk/pxUVWGYC1GMuiNPS7gnKuEgZKfg+tLX3n6AAuQc2cEPy3P2+loG3zt2zfwuCnV0qOm4LUGKzW8lmHVXuC/zWzqncTOa7HUk5B1IsPLJHW+NttcJJmTf9JZPaa0r57Mg==
      MAILER_SMTP_PASSWORD: AgAVj8s0RYPHnZqvQtkx7fAk6VTJiKBsMnmOkSjscxsULkCbglyuYP+JlQHO/ucf679fwLmUGDODCU3SY+QFYctePrz24WrtXeq5m101LVfQITmQr0jH0nIm53L7kII79CLYNRB6WDr9o1xoVTAj867OxPfKrKZJqI2Ijc2Elnmij5FnbxqJMQoo6SdVqvyPPe2X4wluhDxjHD0dERk3Fl2y/16OBlr2ANFzIUHNla1NKrrsmuk3D5byk5fOfEF/Rme3rPO5Un9+TqLWsTaAdiNC0j65hBRhGdrlJ1iNaRPNiQsCpbDjdL/Q+maFu9H4dvvKwhWoOi19Xw/CAFnwzNMHnrCePBHviUhPCAg0V+pmqy0Tm0NMfAs+yHj9ftQYcNPSWhiehfad2JdL82r6p30MWYmRQA+5K1EyNGxe84IEo7AlTgCTpuJInqdpDTMga8FKXirfoZ39brkqAIhHO/YOViJTzmc5UE+T0YUknbolsDOUDkpwVNZnu1MBfIQt8WF5Ume/NFrv90B3MuEe1AFhEMMGWh2np3sGr9OGpAZDlaxjtXJ4lRdPELL5Kx9QskIuQ9lvPYpFeZNDfYHWgGsftPcXGfyZhPctiDcGtYg6leqcH097C8pRMcjRb3QN2sishlWGob4SSr7dZ7QaKtD1NFz6PeahT6yOfxpk0DwHCc9rwfueLOTO/wx4OFJrC64o7uAo0UxXEIGUqys0fFDpUyjywU9SjbPMeV0xXoTWgg==
      MAILER_SMTP_USERNAME: AgB6wAJv10pRfxfoquNDI0CEkcMDVmVcgB2wIpLmyJ+OIR0psk3NMgLxe969vL+vB2fc1H+F7ibWFzXVm77fHDPF/tXy5PXvQ5jiDa4UxaPvtCW9JtPufwVTvDyE29PrgmBuGOYBUaJ/2XI0g8NoI40iOejKegMRsCIBdkKcAeOx1ltCdzErZN+yKc82WxO/6O/rHkPpNCb6SMnjDf4YfipAhz57p4udM6Klcda3vtvzdeoEPcnHHQRmaDZ1Rmt9iwlhb2cV3lr7g1nZn2zkqE/oqcitvkyy7sIFO+H3Usk5OVeDcNDWSE8bSG4bEFtcB8riTExcxAJsmCo7xWd7tYZrX0c3hipdRcY+tCK2QRtrycbIdTXEr6g57cXY56bc6SX/eeTTGq8QcAl3smtZH1GakYF95X5Yk2GXcz9gxjANAYrgkLRFGp3SuI7qI6umCc3NiE1f1RD/hNjXY2mWZd8CqVir2s0s9MxiIFrjeYD7XUhXmIriJs/khsBpdM7YvbRYLFcdSHf2eEgNAkLArWnmyCLxe3V+zqm4VY/zoLH2DgY3HZXLM9/j3bVx1oWDahg7o1sHdmL3gUh3wQvl4p1Ezep5x4O3iGuNLgIAaISFXvHzv2+8tE8pzDLT/U23x6jfikTE5Q/tkLV9Xiwr/fqUiVoK+c9lbg2WsmNMJ2vo1a7hR7t/EQZgxSYSD8Mya9loUHsNccwwp1IaGVjQ0g8R74ozQuXf3zH8a8T9L5LHKQ==
    pprof:
      enabled: true
