apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mailer
    image:
      name: vibioh/mailer
      tag: "202205140815" # {"$imagepolicy": "default:flux-mailer-web:tag"}
    config:
      MAILER_LOGGER_JSON: "true"
      MAILER_MJML_URL: http://mjml
      MAILER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: mailer
    secrets:
      MAILER_AMQP_URI: AgDU9aXXYergLw/jTpePjwGl0xxdQXYWRBF6RZlu1q5wQBjGriF8t8QG81cN4he1Sq2m8ketvSHMwdsm968AbqMLdy+QYbKcmVa8uDgPw7865pWfebS04gigxZLTniSDMKRV3PKPND+5E5wwKAizj81MXn0i8wObjFIEIRmlDknxwIwnGXEuTEvVVR7yLWk7La4ymHm+OkWCwZ5Jx6pDDXF8ZjGf6BWNHYDmTqF17LuS7Esrwc4N0HEW3Vs9A5Uv2xJhmBjQvcS3p6nJu9odKi5BW/VhCzRDwjo1oziN26vv4biz7LGOXpLLoiJSHYwumWfg56FqDxE4CkyHTwMWVgtRalzj8nw5C83bDbQ8l8mZFG+j/KZlvI/E+WmkmRJA6/wz/wTr/RK2Yc4+bs69WkwKIA6vqpdpud9RJx3i5sPjcQrMr3Ij32t1EyNUQBVCc3JiH1dQ/Az+exczrX2S6nsVNDdeKkYP3L45HdM69tsU7N6FuNYku5jPUKMFdHoGPbJP7Ozh/YUKei1OJrKfolajBlPPhFqaHK5tf7jEMM7n3ldFb1XGluWLCFLY+yAZ01zO+HK68rKqUj9SVeWPV4UyS2ZfCOYFxOpT+9KaYOVje/pnbTauzNVZTZePKZ+p0cmJA7s3XyCBuVkMTA0mnrx9NCuyshrTsucVTuJL5TkNAnbIJQHsCeO027bKqMeO31PTTBrFXAQyfIb4qXrbNvwm8ZiZVvmF2iwhs6v1Zp5Gag42OyC9Vx7HeReXnea9W5uslow=
      MAILER_SMTP_ADDRESS: AgBwNzBRu5pfRGaGIz44o+HmcuU5kHkc/A8eikoAcgFRF4SIzMm66USmCQIVT/WhVdcKMwIPmOS0BRfV0kD5zjXr4Rpdp8T6+e58SIEJmgska6vg8XBo/CF0jr6xVDJrA3qpPtncjA4mcLMt/jQ8up1d0K77oBaALWJSnrRyYuBwvQwC++YmwvUBOxtIOGyxPQIDTOk+7AkyZ5Qngfn/ZP+FSENOWNtgklWsl9Hy7NN84jQv0Qk9YMI44vSb3SI19HLDNG9wpQMR6pgPbVqKchnU4r4SZfmus1sXVk9whgv4cAoM6dUrR4zgYeiyFxPgnxnc0Zh0DnbjP+ZQo7W6tqZ7vnVsJclqJeO4awFVmYiXDcO6azdPD5r8zGwqe+780ykaC7lbW9JelMDT1t55CCkuIzQAL4O3ow3WIQoConak1jU9p/1rGP1OlJOI3eh6X/6bmcRJtuHM03aoONxg8Z7MuesRwSLF9dfJY3ismGK01h+M7I7EbvY3j/Ohin276WngTx5bzIWQ7aLX7HX1dTRPCqRafeuuqsnWXuaUpjWeqONnN0NQMqbETJJHX2FromPRUXbJAeI8eIZfWfKcbn88yLC13/Fca4vxL7jNWgK4NG7DNwF5z+29DfZ0GDVOaHLS3iRT4U08wB3rZLUeQPEpdkSRtgqzrpH0mbXz79uUQcichTqmXeBF2/vAo9Y/0aTCyHZPfyYEOcZSQLK2DpWVyjXOLuU=
      MAILER_SMTP_HOST: AgAyn4VoAweqjeKblbCRPSTD4YlbAHt21DTqHuH31Y1Bt9GkUJIkaaAz7u5WzGi2e/GaFHFLJc7lqKmswxYByWCfSvjR2np4XmsKNcwn/iRjAo5zwOnud7tMZNu4h92anb4WKqJ9okQ/RkESdemMqz3GZIeKImrTHEXHCD3hDPe4kD95Drin5atuKLAykfusC4IHx4kACDSudqAa/K/o9oj/VPYJRBepuHJs6qESksWbCpglEz0ZoIGzR0TbWurkkeojdqLmj9L8H12nyCplVVfk3jYlZpeVLyFkLZ1ACQowkbRbwcRwD4FMtN98xu0ToZ8N+ltBYiDF7mesvVFW1oZiagt2LnWuUsZI5BLY913G1x3Ne+6cKzTG0JNwzlZGyKh3nM4RyC3cPv+Op4E6asgi33hfrDxLnVVYCjYodefcjZSUaA55cqX8Mjxl+1z2yfhZqr0o2uai64BQFaXCPUd93CcJER6aI65Pu/6oeViT376mni8dl/SEizG4pb+qZXBMbR2G28Z0jtEc3I772NaguwFGUvyjJsfYewQjIp6jgE3+/uhE4doWis7kA3mDyE/II31Rb51xWUAtZdD54tRAE0xP8ernvpQMxvBHCj/QyO3HaGqIvKJpnVnnT0pjEnyoB1gTLRn3NYzWvXZhNTJYdnVUg4woiK3v+uDP9uEDJLY/Cr1iorkXjPcxJ21YXvJ1Hp0R3SFl9QKmsyF20RBzMg==
      MAILER_SMTP_PASSWORD: AgA/7O/N/3VLqS5ehQTnbUp2wd9BhcWFCHBCbbsBZHqajp8pPBhPrQMrTyqd9Fr/ZqULTTeDhpYgZLSHLvWUoPTc2b04UnQLIHhnWPtAffhH6HLv6cXUhf7V/pQ7af+SlxNkJkA7to0XmvUASNkR8hkFOPrMXVObSocVOAeuclHe95FR3HsBAtJQvLTVoPAReJMpTOSGaLxhUMAQUS5uThML9hE2BgpGOM0sTe7HCVbAqXOsnsZE4Kt9D31QibLj5rUAXFmDjK3RF/eOkznamVQT1WXGvfnaj84NQAD7NPC+1Jtj2XwRbaDG7S+67gqt7Gi/rkhWV2J+/PSYKcvXvTizbhtWnCyN2c3cmPNjPwQq/X4ZHl2Rl0vi413c06rYp8kMq8PB8oTg4qOnk3uskHZjLuJVsnzU23cOA2kERWWcLsZCuAM/YmmhVCbmwH7QgXiLy5KOTOaL/7pRebhBAF4H/E3LK99KQpVlOZi3WPNkJ+wewUypDFgpjyR4B7PtJhsDz8qPvvYuYFNacFxGJQxjtv1cz9GOPKpCNEOpl4W+2/o/OTsrkjJ2+ihs5KIYH5GQ9ZqJVt7Bf9lKokS3NyzfgxynecStfrUXxcRBIHwbY1j+rjd8e6Rls7AAG0/5IDZVnvPKqFJbLkiRd2aFrG7g5rWbCEY5Xbde8s28vQuFsRlOrbajQTI6khwd/ejZ3HJWMgYlAZlKeQyJgGZ55VDLnxOPfD1PubEhLiamvIbWzg==
      MAILER_SMTP_USERNAME: AgBDgJX12Uq8zQuquzXU3ObVpxLaRBY3u+U+1OYQgiRtpWrkTmOuFwSyKFhZKRcMTarY0IHDfByxP49nJZGMmLlfOJxXDXs1y5A2UxM9Nwff2kaqdgRjNDgrx9m2ifSPdpmFhlvuZiIGPTbg60JGlyv+717siux8z4DFdYu4d2LgIL2KGGoOLHSEgKT8njOQYKVhXuzEH1oYy4RR0VYsqkpxpv3xaEQB+3gStW092KaKO++VaKeWMCb9e5cDgR85Dph2dpTK7/rYPLdXRRdVqIyLbIGpgsbJ2yKCpmHISOeuN+X7kFcf09qJntDGFqSFgR4bZ5XQ1yls9VUR5oRAHzfXEtRtt84rnXukV6PHYfIBc5yUxSlPgc80FkYf6l0p7fTw78nQ1HOcjsas/0R/UBB+cIekW0vt0U/3wBJ8dtRAMGV0hVEyXyx5a+QeQ34nUEJ9ceBgnPx8yE6X/5G2qyiS5lXtHqe+cOTkoEFdsIkpl988PcZsv5s8bdYBovWleLGN+ifjBeDnIGouN6X/ZzG+k4nr5ncfjA5aLHlcJp1z+avAbT9t8YKpomXHfIiREWAzxnDfG/WkPrf/1L8GJnblS6m6wfZE6pvImfdJQcnq7xsUqZCOXEE/XkvUMfYAeblxik7WXV/Oj1MtVA1c8IthIVNKJ3ZVTImBzw00vK9daFw3MuwkSAWkMmjwMe/PiEEg4BoQDDTctojvFoz8yeuTsEAGOBW3zuh0I7Mnv7ID8g==
    pprof:
      enabled: true
