
openapi: 3.0.0
info:
  description: Render and send email
  title: Mailer
  version: '1.0.0'

paths:
  /health:
    get:
      description: Healthcheck of app
      responses:
        '204':
          description: Everything is fine

  /version:
    get:
      description: Version of app

      responses:
        '200':
          description: Version of app
          content:
            text/plain:
              schema:
                type: string

  /render/:
    get:
      description: List templates

      responses:
        '200':
          description: List of availables templates
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    description: Templates' name
                    items:
                      type: string

  /render/{template}:
    parameters:
    - name: template
      in: path
      description: Template's name
      required: true
      schema:
        type: string

    get:
      description: Render template
      parameters:
      - name: fixture
        in: query
        description: Fixture's name
        schema:
          type: string

      responses:
        '200':
          description: Render template for fixture
          content:
            text/html:
              type: string

    post:
      description: Render and send template
      parameters:
      - name: from
        in: query
        description: From value of email
        schema:
          type: string
      - name: sender
        in: query
        description: Sender name of email
        schema:
          type: string
      - name: subject
        in: query
        description: Email subject
        schema:
          type: string
      - name: to
        in: query
        description: Recipients of email, comma separated
        schema:
          type: string
      requestBody:
        description: Payload of content
        required: true
        content:
          application/json:
            schema:
              type: object

      responses:
        '200':
          description: Render and send template
        '400':
          description: Invalid parameters for sending
        '500':
          $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      description: Internal server error
      content:
        text/plain:
          schema:
            type: string
